ktor:
    application:
        modules:
            - com.dmytroherez.savingstrack.server.ApplicationKt.module
    deployment:
        port: 8080

storage:
    jdbcURL: ${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASSWORD}